fallback-grpc-addr: 127.0.0.1:3030
order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8282 
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

consul:
  addr: http://110.42.248.168:8500

rabbitmq:
  host: 110.42.248.168
  port: 5672
  user: guest
  password: guest

stripe-key: "$STRIPE_KEY"
stripe-webhook-secret: "$STRIPE_WEBHOOK_SECRET"
local: true

jaeger:
  url: 110.42.248.168:4318
